# Generated by Django 5.0.4 on 2024-04-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_savingaccount_a_number_savingaccount_ocupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingaccount',
            name='a_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='savingaccount',
            name='ocupation',
            field=models.CharField(max_length=20),
        ),
    ]
