# Generated by Django 5.0.4 on 2024-04-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_savingaccount_loan_savingaccount_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='image',
            field=models.ImageField(null=True, upload_to='uimg/'),
        ),
    ]
